name = "kongsian-db-migrations"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kongsian-db"
database_id = "94a52c2f-af08-4642-b477-4edc2251f52b"
migrations_dir = "./migrations"
