name = "kongsian-db-migrations"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kongsian-db-apac"
database_id = "477704de-7334-46aa-8b70-4ee8cfbbad3e"
migrations_dir = "./migrations"
